### ISSUE TITLE
Major change:index page 

### ISSUE THREAD

**Issue by Cistroncoder** [Ozonplay/ozonplay_v1#4]
1. Put slider code outside the header tag.
2. Put slider and section code inside the location: src/app/home/home.component.html
    **I already mentioned it earlier on the app page when you first time run it**
3. add base tag "<base href='\'>"

**Comment by ashishahujaa450** [comment]
close done

**Comment by ashishahujaa450** [comment]
close #4

**Comment by ashishahujaa450** [comment]
closes #2

**Comment by Cistroncoder** [comment]
now all working ok this issue is closed after checking
